spring:
  application:
    name: estagios
  datasource:
    url: jdbc:mysql://localhost:3306/estagios
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true

security:
  jwt:
    access-token-expiration-minutes: 60
    refresh-token-expiration-minutes: 1440
    access-token-secret-key: verysecretkeyohmygodwhyisitsosecretdonttellanybody
    refresh-token-secret-key: anotherverysecretaccesskeydonteverletitleak

#spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
