# General Spring
spring:
  application:
    name: app-name
  datasource:
    url: jdbc:mysql://localhost:3306/database-name
    username: user
    password: pwd
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: false
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    serialization:
      write-dates-as-timestamps: false


springdoc:
  swagger-ui:
    try-it-out-enabled: true
    filter: true
    operations-sorter: 'alpha'
    display-request-duration: true
    deep-linking: true
    show-common-extensions: true
    syntax-highlight:
      activated: true
      theme: 'nord'
  writer-with-default-pretty-printer: true


# CUSTOM SECURITY PROPERTIES
security:
  jwt:
    access-token-expiration-minutes: 60
    refresh-token-expiration-minutes: 1440
    access-token-secret-key: makealongsecret
    refresh-token-secret-key: makeareallongsecret


#DEFAULT SERVER.ERROR CONFIGS
server:
  port: 8080
  error:
    include-binding-errors: never
    include-exception: false
    include-message: never
    include-stacktrace: never
    whitelabel:
      enabled: true
    path: /error

#LOGS
logging:
  level:
    org.springframework.security.web.FilterChainProxy: info
