spring:
  application:
    name: estagios
  datasource:
    url: jdbc:mysql://localhost:3306/estagios
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
#  security:
#    filter:
#      order: 2
#  cache:
#    jcache:
#      provider: com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider
#    cache-names:
#      - rate-limit-buckets
#    caffeine:
#      spec: maximumSize=100000,expireAfterAccess=3600s

#  cache:
#    jcache:
#      provider: com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider
#    cache-names:
#      - rate-limit-buckets
#    caffeine:
#      spec: maximumSize=100000,expireAfterAccess=3600s
#

#bucket4j:
#  enabled: true
#  filters:
#    - cache-name: rate-limit-buckets
#      url: .*
#      strategy: first
#      http-response-body: "{ \"status\": 429, \"error\": \"Too Many Requests\", \"message\": \"You have exhausted your API Request Quota\" }"
#      rate-limits:
#        - cache-key: "getRemoteAddr()"
##          execute-condition: "getHeader('X-api-key').startsWith('PX001-')"
#          bandwidths:
#            - capacity: 5
#              time: 30
#              unit: seconds
#        - cache-key: "getHeader('X-api-key')"
#          execute-condition: "getHeader('X-api-key').startsWith('BX001-')"
#          bandwidths:
#            - capacity: 40
#              time: 1
#              unit: hours
#        - cache-key: "getHeader('X-api-key')"
#          bandwidths:
#            - capacity: 20
#              time: 1
#              unit: hours


# CUSTOM SECURITY PROPERTIES
security:
  jwt:
    access-token-expiration-minutes: 60
    refresh-token-expiration-minutes: 1440
    access-token-secret-key: verysecretkeyohmygodwhyisitsosecretdonttellanybody
    refresh-token-secret-key: anotherverysecretaccesskeydonteverletitleak


#DEFAULT SERVER.ERROR CONFIGS
server:
  error:
    include-binding-errors: never
    include-exception: false
    include-message: never
    include-stacktrace: never
    whitelabel:
      enabled: true
    path: /error

logging:
  level:
    org.springframework.security.web.FilterChainProxy: info
#spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect

#rate-limit:
#  bandwith-capacity: 10
#  refill-per-minute: 10
