spring:
  application:
    name: estagios
  datasource:
    url: jdbc:mysql://localhost:3306/estagios
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true


# CUSTOM SECURITY PROPERTIES
security:
  jwt:
    access-token-expiration-minutes: 60
    refresh-token-expiration-minutes: 1440
    access-token-secret-key: verysecretkeyohmygodwhyisitsosecretdonttellanybody
    refresh-token-secret-key: anotherverysecretaccesskeydonteverletitleak


#DEFAULT SERVER.ERROR CONFIGS
server:
  error:
    include-binding-errors: never
    include-exception: false
    include-message: never
    include-stacktrace: never
    whitelabel:
      enabled: true
    path: /error

#LOGS
logging:
  level:
    org.springframework.security.web.FilterChainProxy: info
